#!/usr/bin/env python3
"""Generate xv6 interrupt vector table (256 entries).

Replaces vectors.pl. Each vector pushes its number and jumps to alltraps.
Traps 8, 10-14, 17 have error codes pushed by hardware (no dummy push needed).
All others push a dummy 0 for uniform trapframe layout.
"""

# Traps that the CPU pushes an error code for
ERRCODE_TRAPS = {8, 10, 11, 12, 13, 14, 17}


def gen_vectors() -> str:
    lines = []
    lines.append("# generated by gen_vectors.py -- do not edit")
    lines.append("")

    # 256 handler entry points
    for i in range(256):
        lines.append(f".globl vector{i}")
        lines.append(f"vector{i}:")
        if i not in ERRCODE_TRAPS:
            lines.append("  pushl $0")
        lines.append(f"  pushl ${i}")
        lines.append("  jmp alltraps")
        lines.append("")

    # vectors[] array in .data
    lines.append(".data")
    lines.append(".globl vectors")
    lines.append("vectors:")
    for i in range(256):
        lines.append(f"  .long vector{i}")
    lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    print(gen_vectors())
